import Head from "next/head";
import { useState } from 'react';
import axios from "axios";
import { useSession } from "next-auth/react"
import Link from 'next/link'
import { useRouter } from "next/router";


export default function CreateGroupe() {
    const [groupeName, setName] = useState('');
    const [groupeDesc, setDesc] = useState('');
    const { data: session } = useSession()
    const router = useRouter()

    const handleSubmit = (event) => {
        event.preventDefault();
        const userId = session.user.id
        const data = { groupeName, groupeDesc, userId };
        axios.post('/api/groupe', data)
            .then((response) => {

            })
            .catch((error) => {
                console.error(error);
            });

        router.push("../");

    }
    return (
        <>
            <Head>
                <title>Créer un groupe</title>
                <meta lang='fr' />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
                <link rel="icon" href="/aaaa.webp" />
            </Head>

            <main>
                <div className="navbar">
                    <Link href="/"><button className="sign">Retour</button></Link>
                    <h1>Créer un groupe</h1>
                    <h3>Remindr</h3>
                </div>
                <div className="formContainer">
                    <form onSubmit={handleSubmit} id="groupeForm">
                        <h2>Nom du groupe :</h2>
                        <input type="text" value={groupeName} className="NameInput" required onChange={(e) => setName(e.target.value)}></input>
                        <h2>Description du groupe :</h2>
                        <textarea value={groupeDesc} className="DescInput" required onChange={(e) => setDesc(e.target.value)}></textarea>
                        <button type="submit" className="sign">Créer</button>
                    </form>
                </div>
            </main>
        </>
    )
}